apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: multus-interfaces
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: bond0.410
      type: vlan
      state: up
      vlan:
        base-iface: bond0
        id: 410
      ipv4:
        enabled: false
        dhcp: false
      ipv6:
        enabled: false
        dhcp: false
    - name: br-apps2
      type: linux-bridge
      state: up
      ipv4:
        dhcp: false
        enabled: false
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: bond0.410
