apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-410
  namespace: mano-apps
spec:
  config: '{ "cniVersion": "0.3.1", "name": "macvlan-410", "type": "macvlan", "mode": "bridge", "master": "bond0.410", "ipam": { "type": "static","addresses": [{ "address": "10.0.41.0/25" }]}}'
