apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-410
  namespace: mano-apps
spec:
  config: '{ 
    "cniVersion": "0.3.1", 
    "name": "nad-br-apps", 
    "type": "bridge",
    "bridge": "br-apps2",  
    "ipam": { 
      "type": "whereabouts", 
      "range": "10.0.41.0/25", 
      "range_start": "10.0.41.40", 
      "range_end": "10.0.41.41"}
    }'
