
#file name depends   clusterGroupName in values-global.yaml

clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
  - open-cluster-management             #for ACM
  - openshift-nmstate                   #for NMstate
  - openshift-local-storage             #for LSO
  - openshift-storage                   #for ODF
  - openshift-cnv                       #for CNF
  - quay-enterprise                     #for quay
  - policies  
  - kafka-cluster                       #for Kafka 
    #  - openshift-logging:
    #      annotations:
    #        openshift.io/node-selector: ""
    #      labels:
    #        openshift.io/cluster-monitoring: "true"
    #        argocd.argoproj.io/managed-by: "ebc-multicloud-gitops-hub"
  - openshift-operators-redhat:
      annotations:
        openshift.io/node-selector: ""
      labels:
        openshift.io/cluster-monitoring: "true"
        argocd.argoproj.io/managed-by: "ebc-multicloud-gitops-hub"
  # STF Namespace:  
  - service-telemetry
  #- openshift-cert-manager-operator
  # End of STF related namespaces
  - prom-kafka-adapter                #for prometheus adapter
  - edge-gitops-vms
  - mgmt-apps                         #for applications
  - ansible                           #for ansible

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management

    nmstate:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate  

    lso:
      name: local-storage-operator
      namespace: openshift-local-storage

    odf:
      name: odf-operator
      namespace: openshift-storage  
 
    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv

    quay:
      name: quay-operator
      namespace: quay-enterprise    
        #channel: stable-3.7

        #
        # STF Operator
        #
    openshift-cert-manager:
      name: openshift-cert-manager-operator
      namespace: openshift-cert-manager-operator
      channel: tech-preview

    amq7-interconnect:
      name: amq7-interconnect-operator
      namespace: service-telemetry
      channel: 1.10.x
      
    prometheus:
      name: prometheus
      namespace: service-telemetry    
      channel: beta
      source: community-operators
 
    elasticsearch-eck:
      name: elasticsearch-eck-operator-certified
      namespace: service-telemetry
      channel: stable
      source: certified-operators

    service-telemetry:
      name: service-telemetry-operator
      namespace: service-telemetry
      channel: stable-1.5

        #
        # End STF operators
        #
    kafka:
      name: amq-streams
      namespace: kafka-cluster 
   
    elasticsearch:
      name: elasticsearch-operator
      namespace: openshift-operators-redhat

#   logging:
    #   
    #    Logging operator being installed using charts due to limitation in settting target namespace via values-hub 
    #   
   
    talam:
      name: topology-aware-lifecycle-manager
      namespace: openshift-operators 

    ansible:
      name: ansible-automation-platform-operator
      namespace: ansible 
      source: redhat-operators
      channel: stable-2.3

  projects:
  - hub

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA
    nmstate:
      name: nmstate-crd
      namespace: openshift-nmstate
      path: charts/mgt-hub/nmstate  
      project: hub

    cnv:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      path: charts/mgt-hub/cnv  
      project: hub

    odf:
      name: odf
      namespace: openshift-storage
      path: charts/mgt-hub/openshift-data-foundations  
      project: hub
    
    lso:
      name: local-storage 
      namespace: openshift-local-storage
      path: charts/mgt-hub/lso
      project: hub  

    quay:
      name: quay
      namespace: quay-enterprise
      path: charts/mgt-hub/quay
      project: hub

    kafka:
      name: kafka
      namespace: kafka-cluster
      path: charts/mgt-hub/kafka
      project: hub

    monitoring:
      name: monitoring
      namespace: prom-kafka-adapter
      path: charts/mgt-hub/monitoring
      project: hub  

    gitops:
      name: gitops
      namespace: npss-gitops
      path: charts/mgt-hub/gitops
      project: hub

        #    logging:
        #      name: logging
        #      namespace: openshift-logging
        #      path: charts/mgt-hub/logging
        #      project: hub

    cert-mgr:
      name: cert-mgr
      namespace: openshift-cert-manager-operator
      path: charts/mgt-hub/cert-mgr
      project: hub

    stf:
      name: stf
      namespace: service-telemetry
      path: charts/mgt-hub/stf
      project: hub
  
    edge-gitops-vms:
      name: edge-gitops-vms
      namespace: mgmt-apps 
      project: hub
      path: charts/mgt-hub/vm-on-bm

    ansible:
      name: ansible
      path: charts/mgt-hub/ansible
      project: hub
##### Following are not being used
#  imperative:
#    jobs:
#
#    - name: regional-ca
#      playbook: ansible/playbooks/on-hub-get-regional-ca.yml
#  managedClusterGroups:
#    exampleRegion:
#      name: group-one
#      labels:
#      - name: clusterGroup
#        value: group-one
#      helmOverrides:
#      - name: clusterGroup.isHubCluster
#        value: false

