apiVersion: v1
kind: Service
metadata:
  name: stf-kafka-adapter-svc
  namespace: "{{ adapter_ns }}"
  labels:
    app: stf-prometheus-kafka-adapter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: stf-prometheus-kafka-adapter

