#
# Create route that will be used by OpenStack rsyslog to send logs to ES
#
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: elastic-service-telemetry
  namespace: {{ stf_ns }}
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
spec:
  host: elastic-service-telemetry.apps.{{ mgmt_cluster_name }}.{{ domain }}
  to:
    kind: Service
    name: elasticsearch-es-http
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
