apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "10"
  name: wait-for-stf-prereqs-cert
  namespace: {{ .Values.stf.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: OnFailure
      serviceAccountName: cert-admin-sa
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.job.image }}
        imagePullPolicy: IfNotPresent
        name: wait-for-stf-prereqs-cert
        env:
          - name: SLEEP
            value: "3"
        command:
        - /bin/bash
        - -c
        - |
          echo "STF PreInstall Hook - Check OpenShift Cert Manager Operator"

          # Check OpenShift cert manager operator
          CSV_NAME=$(oc get csv -n  openshift-cert-manager-operator | egrep cert-manager | awk '{print $1}')
          CSV_STATUS="Pausing $SLEEP seconds..."
          while [ "$CSV_STATUS" != "InstallSucceeded" ]; do
            echo "Waiting for the cert mgr Operator to be ready. ($CSV_STATUS)"
            sleep $SLEEP
            CSV_STATUS=$( oc get csv -n openshift-cert-manager-operator $CSV_NAME -o jsonpath={..status.conditions[-1:]} | jq .| egrep reason | awk -F '"' '{print $4}' )
          done

          echo "All done! Hooray!"

