apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  managementState: Managed
  storage:
    pvc:
      claim: image-registry-storage
