---
- name: Include delete_resource.yml
  ansible.builtin.include_tasks: delete_resource.yml
  vars:
    src: 01_worklaod_monitoring.yml

- name: Include delete_project.yml
  ansible.builtin.include_tasks: delete_project.yml
  vars:
    namespace: "{{ monitoring_ns }}"
