---
- name: Install ansible collection - oasis
  ansible.builtin.command: ansible-galaxy collection install oasis_roles.system:==1.3.0
  changed_when: false

- name: Install ansible collection - theforeman
  ansible.builtin.command: ansible-galaxy collection install theforeman.foreman:==3.10.0
  changed_when: false

- name: Install satellite requirements
  ansible.builtin.script: 01_install_satellite_requirements.sh

- name: Install apypie
  become: true
  ansible.builtin.command: pip3 install --user apypie
  changed_when: false

- name: Create directory and copy satellite manifest file
  ansible.builtin.copy:
    dest: "{{ http_store_satellite_path }}/"
    src: "{{ manifest_path }}/{{ manifest_file }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0755"
  notify:
    - Restart http store

#- name: Include create_resource.yml
#  ansible.builtin.include_tasks: create_resource.yml
#  vars:
#    src: 01_satellite_vm.yml
#    ansible_python_interpreter: /usr/bin/python3.9
#
#- name: Wait for ssh connection to be open on Satellite VM
#  ansible.builtin.wait_for:
#    port: 22
#    host: "{{ satellite_ip }}"
#    timeout: 300
#
- name: Copy ssh ID for Satellite VM
  ansible.builtin.command: sshpass -p "{{ satellite_admin_password }}" ssh-copy-id -o StrictHostKeyChecking=no {{ satellite_admin_username }}@{{ satellite_ip }}
  changed_when: true

- name: Generate dynamic inventory
  ansible.builtin.add_host:
    name: "{{ satellite_fqdn }}"
    ansible_user: "{{ satellite_admin_username }}"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      #ansible_python_interpreter: "/usr/bin/python"
      #interpreter_python: "/usr/bin/python"
    groups: satellite

- name: Groups of tasks delegated to satellite VM
  block:
    - name: Run install satellite
      ansible.builtin.include_tasks: install_satellite.yml
    
    - name: Run Configure satellite
      ansible.builtin.include_tasks: configure_satellite.yml
  become: yes
  become_user: root
  delegate_to: "{{ satellite_fqdn }}"
    
- name: Include integrate_with_idm.yml
  ansible.builtin.include_tasks: integrate_with_idm.yml
  when: idm_integration
