- name: quay repo
  hosts: localhost
  vars_files:
    - /home/mano/ebc-multicloud-gitops/playbooks/vars/common.yml    
  tasks: 
    - name: Include populate
      ansible.builtin.include_tasks: populate_repo.yml
