---
# tasks file for quay

- name: login to OCP cluster
  ansible.builtin.include_tasks: cluster_login.yml

- name: Install Quay
  ansible.builtin.include_tasks: install.yml
  when: state|default('present') == 'present'

- name: Uninstall Quay
  ansible.builtin.include_tasks: uninstall.yml
  when: state|default('present') == 'absent'
