apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "30"
  name: config-quay-repo
  namespace: {{ .Values.quay.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image2 }}
        command:
        - /bin/bash
        - -c
        - |
          QUAY_HOSTNAME=quay-registry-quay-quay-enterprise.apps.mgmt.npss.bos2.lab
          oc version
          opm version
          oc-mirror version
          wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/opm-linux.tar.gz
          wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.tar.gz
          mkdir tmp
          mv openshift-client-linux.tar.gz ~/tmp
          mv opm-linux.tar.gz ~/tmp
          cd tmp
          tar -xf openshift-client-linux.tar.gz
          tar -xf opm-linux.tar.gz
          tar xvzf oc-mirror.tar.gz
          chmod +x oc-mirror
          cp oc /usr/local/bin
          cp kubectl /usr/local/bin
          cp opm  /usr/local/bin
          cp oc-mirror /usr/local/bin/
          oc version
          oc-mirror version
          rm -rfv tmp/    
 


        name: config-quay-repo
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60
