---
- name: Create subscription for operator {{ operator_name }}
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    username: "{{ rhocp_user }}"
    password: "{{ rhocp_password }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ subscription_name }}"
        namespace: "{{ namespace }}"
      spec:
        channel: "{{ channel }}"
        name: "{{ operator_name }}"
        installPlanApproval: Manual
        source: "{{ subscription_source | default('redhat-operators') }}"
        sourceNamespace: openshift-marketplace
