---
- name: Create project {{ namespace }}
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    username: "{{ rhocp_user }}"
    password: "{{ rhocp_password }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"

