---
- name: Delete resources
  ansible.builtin.include_tasks: delete_resource.yml
  vars:
    src: "{{ item }}"
  loop:
    - 06_stf.yml
    - 05_image_registry.yml
    - 04_pvc.yml
    - 03_catalog_source.yml

- name: Include delete_project.yml
  ansible.builtin.include_tasks: delete_project.yml
  vars:
    namespace: "{{ item }}"
  loop:
    - "{{ stf_ns }}"
    - "{{ cert_manager_ns }}"
