apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: manocluster-registry
  namespace: quay-enterprise
spec:
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: true
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: false
    - kind: tls
      managed: false
  configBundleSecret: db-config-bundle-secret
