#apiVersion: v1
#kind: Namespace
#metadata:
#  name: openshift-operators-redhat
#  annotations:
#    openshift.io/node-selector: ""
#  labels:
#    openshift.io/cluster-monitoring: "true"
#    argocd.argoproj.io/managed-by: ebc-multicloud-gitops-hub 

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-20"  
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: ebc-multicloud-gitops-hub 


---
#apiVersion: operators.coreos.com/v1
#kind: OperatorGroup
#metadata:
#  name: openshift-operators-redhat
#  namespace: openshift-operators-redhat
#spec: {}

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-15"    
spec:
  targetNamespaces:
  - openshift-logging

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-12"    
spec:
  name: cluster-logging
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"

---
#apiVersion: "logging.openshift.io/v1"
#kind: "ClusterLogging"
#metadata:
#  name: "instance"
#  namespace: "openshift-logging"
#  annotations:
#    argocd.argoproj.io/sync-wave: "-10"    
#spec:
#  managementState: "Managed"
#  collection:
#    logs:
#      type: "fluentd"
#      fluentd: {}

