---
- name: Create subscription for operator {{ operator_name }}
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    username: "{{ rhocp_user }}"
    password: "{{ rhocp_password }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ namespace }}-subscription"
        namespace: "{{ namespace }}"
      spec:
        channel: "{{ channel }}"
        name: "{{ operator_name }}"
        source: redhat-operators
        installPlanApproval: manual
        sourceNamespace: openshift-marketplace
