apiVersion: v1
kind: Namespace
metadata:
  name: "{{ elasticsearch_ns }}"
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ openshift_logging_ns }}"
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
