apiVersion: "{{ openshift_logging_api_version }}"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "{{ openshift_logging_ns }}"
spec:
  managementState: "Managed"
#  logStore: 
#    type: "elasticsearch"
#    retentionPolicy:
#      application: 
#        maxAge: 1d
#      infra:
#        maxAge: 7d
#      audit:
#        maxAge: 7d
#    elasticsearch:
#      nodeCount: 3
#      storage:
#        storageClassName: "ocs-storagecluster-ceph-rbd"
#        size: 200G
#      resources:
#        requests:
#          memory: "8Gi"
#      proxy:
#        resources:
#          limits:
#            memory: 256Mi
#          requests:
#             memory: 256Mi
#      redundancyPolicy: "SingleRedundancy"
#  visualization:
#    type: "kibana"
#    kibana:
#      replicas: 1
#  curation:
#    type: "curator"
#    curator:
#      schedule: "30 3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
