= kafka role

This role allows to install/uninstall Kafka in an OpenShift cluster.

== Requirements

* Ansible 2.9
* OpenShift 4.10

== Role Variables

List of variables used by the role. The ones marked as _required_ need to be added to the playbook.

[cols="4*<.^",options=header]
|===
|Variable |Description | Required | Default 

|kubeconfig_path | Path to the kubeconfig file | Yes | None

|rhocp_user | OpenShift user | Yes | None

|provisioner_ip | IP Address of the provisioner host | Yes | None

|kafka_ns |Namespace used to install the Kafka operator. | No | kafka-cluster

|kafka_operator_name |Name of the Kafka operator. | No | amq-streams

|kafka_channel |Name of the Kafka operator channel. | No | stable

|kafka_api_version |Kafka API version. | No | kafka.strimzi.io/v1beta2

|secrets_path |Directory that stores the secrets used by the automation. | No | secrets_path: ~/secrets

|===

== Examples

Example playbook to install Kafka getting required variables from the playbook_required_vars.yml file:

[source, yaml]
----
- name: Playbook to install Kafka
  hosts: provisioner_host
  vars_file:
    - playbook_required_vars.yml
  roles:
    - role: kafka
      state: present
----

Example playbook to uninstall Kafka getting required variables from the playbook_required_vars.yml file:

[source, yaml]
----
- name: Playbook to uninstall Kafka
  hosts: provisioner_host
  vars_file:
    - playbook_required_vars.yml
  roles:
    - role: kafka
      state: absent
----

== License

TBD

== Author Information

Alaitz Mendiola <alaitz@redhat.com>
