apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/rhel8.8: Red Hat Enterprise Linux 9.0 or higher
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app: "{{ .Values.sat_app_name }}"
    flavor.template.kubevirt.io/medium: "true"
    os.template.kubevirt.io/rhel8.8: "true"
    workload.template.kubevirt.io/server: "true"
  name: "{{ .Values.sat1_hostname }}"
  namespace: "{{ .Values.apps_ns }}"
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: "{{ .Values.sat1_hostname }}-rootdisk-0"
    spec:
      pvc:  #Set acccessModes to RWX and volumeMode to block for live migration and VM pod eviction
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1000Gi
        storageClassName: ocs-storagecluster-ceph-rbd
        volumeMode: Block
      source:
        http:
          url: http://{{ .Values.provisioner_ip }}/{{ .Values.sat_qcow }}
  running: true
  template:
    metadata:
      labels:
        flavor.template.kubevirt.io/medium: "true"
        kubevirt.io/domain: "{{ .Values.sat_domain }}"
        kubevirt.io/size: large
        os.template.kubevirt.io/rhel8.8: "true"
        vm.kubevirt.io/name: "{{ .Values.sat_domain }}"
        workload.template.kubevirt.io/server: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      domain:
        cpu:
          cores: 16
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: nic-1
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 32Gi
      evictionStrategy: LiveMigrate
      hostname: "{{ .Values.sat1_hostname }}"
      networks:
        - multus:
            networkName: "{{ .Values.apps_nad_name }}"
          name: nic-1
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_pwauth: True
              user: {{ .Values.sat_user }}
              password: {{ .Values.sat_password }}
              chpasswd:
                expire: false
            networkData: |
              version: 2
              ethernets:
                eth0:
                  addresses:
                  - "{{ .Values.sat1_ip }}/{{ .Values.apps_subnet_len }}"
                  gateway4: "{{ .Values.apps_subnet_gw }}"
                  nameservers:
                    search: [{{ .Values.domain }}]
                    addresses: [{{ .Values.dns_server_ip}}]
          name: cloudinitdisk
        - dataVolume:
            name: "{{ .Values.sat1_hostname }}-rootdisk-0"
          name: rootdisk

