---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cert-manager-operator
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-20"  
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: ebc-multicloud-gitops-hub 

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: openshift-cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-15"    
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: openshift-cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-12"    
spec:
  channel: tech-preview
  installPlanApproval: Automatic
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

